### ISSUE TITLE
帳號資訊頁面 Server Error (500)

### ISSUE THREAD

**Issue by bananaappletw** [NCTU-OAuth/issue-report#1]
![default](https://cloud.githubusercontent.com/assets/6241350/18230832/cf670648-72d9-11e6-9672-20c67fe08fcf.png)

**Comment by iblislin** [comment]
@bananaappletw 同學您是不是沒有 d2 帳號？

**Comment by bananaappletw** [comment]
@iblis17 是的
好的我申請看看後再試試看
感謝

**Comment by pellaeon** [comment]
我們已經確認是因為沒有 d2 帳號造成 500 ，目前已經有 patch ，正在 review 中，patch 部署後會告知，感謝。

**Comment by bananaappletw** [comment]
剛剛申請 d2 帳號後正常了
感謝
