### ISSUE TITLE
交大資工系上帳號串接 NCTU OAuth

### ISSUE THREAD

**Issue by mangokingTW** [NCTU-OAuth/issue-report#2]
我代表交大資工系計中助教，想詢問 NCTU OAuth 的狀態。
我們系上有一個獨立的帳號系統，希望能藉由您們的服務確認學生身份。
需要學號、姓名、E-mail、系級、在學狀態，經查證後都有提供。
但是做為系上服務，必須確保資料的正確性。
請問您們的資料是直接接上學校的帳號系統嗎? 或是另外透過同步的方式呢?
另外，這個系統的維運人員是校方職員嗎? 系統有無可能被中止?
希望提供以上資訊讓我們參考，謝謝。

系計中助教 顏靖軒

**Comment by yuchingtw** [comment]
是的，是直接串上學校的帳號系統，也是校計中維護的。
此外現在主要使用 NYCU OAuth (id.nycu.edu.tw)，NCTU OAuth (id.nctu.edu.tw) 已不會在維護。
