### ISSUE TITLE
無法登入

### ISSUE THREAD

**Issue by chinghuang1101** [NCTU-OAuth/issue-report#7]
ＩＣＴ的登入頁面要求帳號密碼與交大單一路口的一樣，但我可以同一組帳號密碼登進去單一路口，卻無法登進去ＩＣＴ的空間借用系統。麻煩盡快處理，謝謝！

**Comment by iblislin** [comment]
id.nctu.edu.tw 看起來是正常可以登入？
那麼 ICT 是哪個網頁？

**Comment by yuchingtw** [comment]
ICT 現在應該已經改為串接 NYCU OAuth (id.nycu.edu.tw)，用現在能登進 portal 的帳密試試看呢？
