### ISSUE TITLE
NCTU+無法登入

### ISSUE THREAD

**Issue by shaolunchen** [NCTU-OAuth/issue-report#8]
我想登入NCTU+網站，上面說要用單一入口帳密登入，但我用該帳密卻無法登入，請問能不能幫忙解決此問題？謝謝

**Comment by yuchingtw** [comment]
可能是因為 NCTU+ 還是串 NCTU OAuth (id.nctu.edu.tw)，用併校前的帳號登入看看呢？

**Comment by shaolunchen** [comment]
但我是大一新生，沒有併校前帳號

YuChing Chen ***@***.***> 於 2021年11月23日 週二 上午10:24寫道：

**Comment by yuchingtw** [comment]
那可能要 NCTU+ 支援才有辦法
